services:
  nginx:
    container_name: "nginx"
    image: "nginx:latest"
    volumes:
      - "./etc/nginx/conf.d:/etc/nginx/conf.d"
      - "./etc/nginx/certs:/etc/nginx/certs"
    networks:
      - "nginx"
      - "pihole"
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"

networks:
  nginx:
    external: "true"
