---
- name: install wireguard
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - qrencode
    - wireguard

- name: generate key pair
  ansible.builtin.shell:
    cmd: umask 077 && wg genkey | tee private_key | wg pubkey > public_key
    chdir: /etc/wireguard 
    creates: /etc/wireguard/public_key

- name: get private key
  ansible.builtin.shell:
    cmd: cat /etc/wireguard/private_key
  register: private_key
  changed_when: false

- name: get public key
  ansible.builtin.shell:
    cmd: cat /etc/wireguard/public_key
  register: public_key
  changed_when: false

- name: set server private key fact
  ansible.builtin.set_fact:
    private_key: "{{ private_key.stdout }}"

- name: set server_public key fact
  ansible.builtin.set_fact:
    public_key: "{{ public_key.stdout }}"

- name: wg0.conf
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
    force: false

- name: create /etc/wireguard/clients
  ansible.builtin.file:
    path: /etc/wireguard/clients
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: add clients
  include_tasks: add_clients.yaml
  loop: "{{ lookup('dict', wireguard.clients) }}"
  loop_control:
    loop_var: client

- name: enable ip forwarding
  include_tasks: enable_ip_forwarding.yaml

- name: update dns record
  include_tasks: update_dns_record.yaml

- name: start wireguard and enable on boot
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started