services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    volumes:
      - ./etc/pihole:/etc/pihole
      - ./etc/dnsmasq.d:/etc/dnsmasq.d
    networks:
      - pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      FTLCONF_dns_listeningMode: SINGLE
      FTLCONF_dns_interface: <your_interface_here>
      FTLCONF_dns_upstreams: <your_upstream_dns_here>
      FTLCONF_webserver_api_password: ${PASSWORD}
      TZ: <your_timezone_here>
    restart: unless-stopped

networks:
  pihole:
    external: true
