services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./etc/pihole:/etc/pihole"
      - "./etc/dnsmasq.d:/etc/dnsmasq.d"
    environment:
      FTLCONF_dns_listeningMode: SINGLE
      FTLCONF_dns_interface: <your_interface_here>
      FTLCONF_dns_upstreams: '<your_upstream_dns_1_here>;<your_upstream_dns_2_here>'
      FTLCONF_webserver_api_password: '${PASSWORD}'
      TZ: '<your_timezone_here>'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.rule=Host(`<your_fqdn_here>`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  pihole:
    external: true
